### ISSUE TITLE
`P` errors on numbers

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#345]
When given two numbers as arguments, the `P` command errors.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI0MjAgNjkgUCIsIiIsIiJd)

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Vyxal/mysite/vyxal/main.py", line 146, in execute_vyxal
    exec(code)
  File "<string>", line 1, in <module>
  File "/home/Vyxal/mysite/vyxal/elements.py", line 3128, in strip
    return {
  File "/home/Vyxal/mysite/vyxal/elements.py", line 3130, in <lambda>
    vy_str(lhs).strip(vy_str(rhs), ctx)
TypeError: strip expected at most 1 argument, got 2
```

**Comment by cgccuser** [comment]
Trivial fix, the `ctx` should just be removed, I'll do it in a few minutes.
