### ISSUE TITLE
LazyList issue in Title Casing lambda

### ISSUE THREAD

**Issue by TheSecondComing123** [Vyxal/Vyxal#477]
I have this code:

```
λW`A`•;ð/
```

This code should take a string, split it by spaces, and capitalize each word. Instead, this error occurs:

```
Traceback (most recent call last):
  File "/home/Vyxal/mysite/vyxal/main.py", line 147, in execute_vyxal
    exec(code, locals() | globals())
  File "<string>", line 30, in <module>
  File "/home/Vyxal/mysite/vyxal/elements.py", line 725, in divide
    return {
  File "/home/Vyxal/mysite/vyxal/elements.py", line 732, in <lambda>
    }.get(ts, lambda: vectorise(divide, lhs, rhs, ctx=ctx))()
  File "/home/Vyxal/mysite/vyxal/elements.py", line 3596, in vectorise
    ts = primitive_type(lhs), primitive_type(rhs)
  File "/home/Vyxal/mysite/vyxal/helpers.py", line 541, in primitive_type
    assert type(item) in [list, LazyList]
AssertionError
```

Note: I am testing this with the input `hello world`.
Note: I am testing this code on [this site](https://vyxal.pythonanywhere.com/).

**Comment by AMiller42** [comment]
I pretty much just assumed that this was a LazyList issue when I saw `assert type(item)` in the traceroute, so this is my bad. The error is actually happening because `/` doesn't have an overload for functions.
